# Generated by Django 5.2.8 on 2025-11-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qoute',
            new_name='Quote',
        ),
    ]
