# Generated by Django 5.2.8 on 2025-11-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_qoute_quote'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.UniqueConstraint(fields=('quote', 'amount'), name='unique_transaction_quote_amount'),
        ),
    ]
