# Generated by Django 5.2.8 on 2025-11-13 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_quote_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='state',
        ),
    ]
