# Generated by Django 5.2.8 on 2025-11-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_transaction_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='converted_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
