# Generated by Django 5.2.8 on 2025-11-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_quote_converted_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-update_timestamp', '-timestamp']},
        ),
        migrations.AddField(
            model_name='rate',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
